spring.application.name: app-code-test


server:
  port: 8082

deadcode:
  static-scan: true
  repo: https://github.com/rajkirancs44/dead-code-analyzer.git
  branch: main
  base-packages:
    - com.citi.analyzer
  track-execution-time: true
  track-invocation-count: true
  analyzer-base-url: http://localhost:8081
  dump-interval-time: 100