spring.application.name: app-code-test


server:
  port: 8082

deadcode:
  static-scan: true
  repo: https://github.com/rajkirancs44/app-code-test.git
  branch: main
  base-packages:
    - com.citi.test
  track-execution-time: true
  track-invocation-count: true
  analyzer-base-url: http://localhost:8081
  dump-interval-time: 100
  stats-dump-interval-time: 180
  stats-scan: true
